---

del_old_pkg : 
  - docker.io 
  - docker-doc 
  - docker-compose 
  - podman-docker 
  - containerd 
  - runc
pre_pkg_install : 
  - curl 
  - gnupg2 
  - ca-certificates

docker_repo_gnupg_folder : /etc/apt/keyrings
docker_repo_gnupg_file: "{{docker_repo_gnupg_folder}}/docker.asc"
docker_repository: "deb [arch=amd64 signed-by={{docker_repo_gnupg_file}}] https://download.docker.com/linux/{{ ansible_distribution | capitalize }} {{ ansible_distribution_release | capitalize }} stable"
docker_pkg_install:  
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin
