---

- name: Delete old package
  apt:
    name: "{{ del_old_pkg }}"
    state: absent

- name: Update repository
  apt:
    update_cache: yes

- name: Install prerequesite package
  apt:
    name: "{{ pre_pkg_install }}"
    update_cache: yes